server.port=8081

kite.api-key=4h3unavc8qqt1gw6
kite.api-secret=7eue5ev7ds9g2ljc6dl23w9opch8bomf
kite.redirect-url=http://localhost:8081/callback

server.tomcat.redirect-context-root=false

logging.level.com.pradip.tradingbot=DEBUG