server.port=8081

kite.api-key=z8e63rqeo3thfz20
kite.api-secret=pu7hjst805kx5gulpy1ictoqsa27spxu
kite.redirect-url=http://localhost:8081/callback

server.tomcat.redirect-context-root=false

logging.level.com.pradip.tradingbot=DEBUG