server.port=8081

kite.api-key=z8e63rqeo3thfz20
kite.api-secret=raps7489ez31xyhhc8d4ngtpmibr8b5l
kite.redirect-url=http://localhost:8081/callback

server.tomcat.redirect-context-root=false

logging.level.com.pradip.tradingbot=DEBUG